name: cargo_cache
description: 'Prepare the Cache of Rust'
inputs:
  cache-key:
    description: 'the rust cache key suffix'
    required: false
    default: ''
  cache-platform:
    description: 'the platform that rust run on'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target
        key: ${{ runner.os }}-cargo-${{ inputs.cache-platform }}-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.cache-key }}
        restore-keys: |
            ${{ runner.os }}-cargo-${{ inputs.cache-platform }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-${{ inputs.cache-platform }}
            ${{ runner.os }}-cargo